// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "brands" section.

import React from 'react';
import FeaturesRevealCards from '@/components/sections/features/FeaturesRevealCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function BrandsSection(): React.JSX.Element {
  return (
    <div id="brands" data-section="brands">
        <SectionErrorBoundary name="brands">
              <FeaturesRevealCards
          tag="Nos Marques Sélectionnées"
          title="Partenaires Dermatologiques de Classe Mondiale"
          description="Nous sélectionnons uniquement les marques dermo-cosmétiques de la plus haute qualité pour garantir à votre peau les soins professionnels qu'elle mérite."
          items={[
            {
              title: "La Roche-Posay",
              description: "Soins recommandés par les dermatologues pour les peaux sensibles.",
              imageSrc: "https://images.pexels.com/photos/27694097/pexels-photo-27694097.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=27694097",
            },
            {
              title: "Avène",
              description: "Soothing care based on the power of thermal spring water.",
              imageSrc: "https://images.pexels.com/photos/5517064/pexels-photo-5517064.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=5517064",
            },
            {
              title: "Caudalie",
              description: "Soins naturels à base de vigne alliant science et beauté.",
              imageSrc: "https://images.pexels.com/photos/11911818/pexels-photo-11911818.jpeg?auto=compress&cs=tinysrgb&h=650&w=940&id=11911818",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
