// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Visitez Kiko Beauty"
          text="Prêt à revitaliser votre peau ? Passez à notre boutique aujourd'hui pour une consultation personnalisée."
          primaryButton={{
            text: "Obtenir l'itinéraire",
            href: "#",
          }}
          secondaryButton={{
            text: "Nous envoyer un message",
            href: "#",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
