// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from '@/components/sections/faq/FaqTwoColumn';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTwoColumn
          tag="Besoin d'aide ?"
          title="Questions Fréquemment Posées"
          description="Vous avez des questions ? Nous sommes là pour vous guider."
          items={[
            {
              question: "Où êtes-vous situés ?",
              answer: "Nous sommes idéalement situés au centre-ville de Marrakech.",
            },
            {
              question: "Are your products authentic?",
              answer: "Yes, we source directly from official authorized distributors.",
            },
            {
              question: "Do you provide skin consultations?",
              answer: "Yes, our team is trained to offer personalized dermo-cosmetic advice.",
            },
            {
              question: "Do you carry specific brands?",
              answer: "We stock La Roche-Posay, Avène, Caudalie, SVR, and many more.",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
