// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "home" section.

import React from 'react';
import HeroSplitVerticalMarqueeTall from '@/components/sections/hero/HeroSplitVerticalMarqueeTall';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HomeSection(): React.JSX.Element {
  return (
    <div id="home" data-section="home">
        <SectionErrorBoundary name="home">
              <HeroSplitVerticalMarqueeTall
          tag="Kiki Beauty Store Marrakech"
          title="Votre Partenaire Beauté Parapharmacie de Confiance"
          description="Découvrez des dermo-cosmétiques premium au cœur de Marrakech. Des conseils d'experts et des marques de renommée mondiale comme La Roche-Posay, Avène et Caudalie."
          primaryButton={{
            text: "Explorer les Produits",
            href: "#products",
          }}
          secondaryButton={{
            text: "Nous Rendre Visite",
            href: "#contact",
          }}
          leftItems={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/woman-having-peeling-with-gloves-turkish-hamam_140725-1694.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-bottles-with-dispensers-liquid-soap_169016-23454.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/life-style_1122-1803.jpg",
            },
          ]}
          rightItems={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/spa-composition-with-hygiene-items-top-view_169016-29208.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-glass-metal-salt-pepper-shaker-set-table_140725-12894.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/dreamy-aesthetic-cosmetic-product-with-fresh-background_23-2151382913.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
