// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "products" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ProductsSection(): React.JSX.Element {
  return (
    <div id="products" data-section="products">
        <SectionErrorBoundary name="products">
              <FeaturesImageBento
          tag="Notre Catalogue"
          title="Essentiels de Soin Sélectionnés"
          description="Parcourez notre sélection de produits de beauté haute performance et de soins dermo-cosmétiques."
          items={[
            {
              title: "La Roche-Posay Effaclar",
              description: "Soin anti-imperfections pour une peau nette.",
              imageSrc: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&q=80&w=800",
            },
            {
              title: "Age Control",
              description: "Rejuvenate naturally.",
              imageSrc: "http://img.b2bpic.net/free-photo/candles-essential-oil-bottle-rhassoul-clay-la-stone-himalayan-rock-salt-tray-against-black-concrete-backdrop_23-2148087673.jpg",
            },
            {
              title: "Cleansing Gel",
              description: "Pure clarity.",
              imageSrc: "http://img.b2bpic.net/free-photo/luxury-cream-jar-with-golden-lid-spatula_9975-133794.jpg",
            },
            {
              title: "Night Repair",
              description: "Wake refreshed.",
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-refillable-reusable-container_23-2150936088.jpg",
            },
            {
              title: "Sun Protection",
              description: "Guard your health.",
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-woman-working-photography-studio_23-2150254643.jpg",
            },
            {
              title: "Brightening Serum",
              description: "Radiance revealed.",
              imageSrc: "http://img.b2bpic.net/free-photo/3d-rendering-personal-care-products-fondant-pink_23-2151053850.jpg",
            },
            {
              title: "Hand Recovery",
              description: "Soften daily.",
              imageSrc: "http://img.b2bpic.net/free-photo/flat-lay-serum-bottles-with-creme_23-2148549097.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
