// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialRatingCards from '@/components/sections/testimonial/TestimonialRatingCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialRatingCards
          tag="Ils nous font confiance"
          title="Ce que disent nos clients"
          description="Rejoignez notre communauté de passionnés de soins de la peau satisfaits à Marrakech."
          testimonials={[
            {
              name: "Amira S.",
              role: "Cliente",
              quote: "Les conseils d'experts que j'ai reçus ici ont complètement transformé ma peau.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-woman-working-pharmaceutical-industry_23-2151684864.jpg",
            },
            {
              name: "Fatima Z.",
              role: "Client",
              quote: "Best selection of authentic La Roche-Posay and Caudalie products.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/woman-using-mobile-phone-while-resting-home_1163-3832.jpg",
            },
            {
              name: "Yassine M.",
              role: "Client",
              quote: "Fast, professional, and knowledgeable. Highly recommended.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-beautiful-woman-smiling-while-taking-some-facial-cream-isolated-white-background-with_1258-133044.jpg",
            },
            {
              name: "Laila K.",
              role: "Client",
              quote: "A beautiful shop with genuinely helpful staff.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/skin-care-after-effect-smiling-young-woman-with-healthy-hydrated-moisturized-natural-skin-touching-face-near-jawline-look-pleased-cosmetic-treatment-from-acne-blemishes-pure-pores_176420-45111.jpg",
            },
            {
              name: "Hicham A.",
              role: "Client",
              quote: "My go-to place for all my dermo-cosmetic needs in Marrakesh.",
              rating: 5,
              imageSrc: "http://img.b2bpic.net/free-photo/medium-shot-girl-shopping-bags_23-2148225697.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
